#Name: Tian Ye
#Email: tianyesh@gmail.com
#ID: 704931660

default:
	gcc -Wall -Wextra -g lab3a.c -lm -o lab3a
dist: default
	tar -czvf lab3a-704931660.tar.gz Makefile README lab3a.c ext2_fs.h
clean:
	rm lab3a *.tar.gz
